"""add normalized measurements table

Revision ID: 84fc51d05768
Revises: 1edec7254909
Create Date: 2026-09-01 10:42:45.325447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fc51d05768'
down_revision: Union[str, Sequence[str], None] = '1edec7254909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('measurement_point_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('quality', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_packet_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('value IS NULL OR value_bool IS NULL', name='ck_measurements_single_value'),
    sa.ForeignKeyConstraint(['measurement_point_id'], ['measurement_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('measurement_point_id', 'window_start'),
    postgresql_partition_by='RANGE (window_start)'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
