"""simplify device credential status, make device water_object_id nullable, add device_activation_codes table

Revision ID: 5ef5bd9329a0
Revises: e4bbf30c8cc5
Create Date: 2026-08-23 10:43:51.391493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef5bd9329a0'
down_revision: Union[str, Sequence[str], None] = 'e4bbf30c8cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_activation_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_credential_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_credential_id'], ['device_credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redeemed_by_credential_id')
    )
    op.create_index(op.f('ix_device_activation_codes_code_hash'), 'device_activation_codes', ['code_hash'], unique=True)
    op.create_index(op.f('ix_device_activation_codes_status'), 'device_activation_codes', ['status'], unique=False)
    op.add_column('device_credentials', sa.Column('activation_code_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'device_credentials', 'device_activation_codes', ['activation_code_id'], ['id'])
    op.drop_column('device_credentials', 'pending_water_object_id')
    op.alter_column('devices', 'water_object_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'water_object_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('device_credentials', sa.Column('pending_water_object_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device_credentials', type_='foreignkey')
    op.drop_column('device_credentials', 'activation_code_id')
    op.drop_index(op.f('ix_device_activation_codes_status'), table_name='device_activation_codes')
    op.drop_index(op.f('ix_device_activation_codes_code_hash'), table_name='device_activation_codes')
    op.drop_table('device_activation_codes')
    # ### end Alembic commands ###
