"""add telemetry packets table

Revision ID: 98f8f151d0b5
Revises: ad166fc97277
Create Date: 2026-08-05 10:28:19.516143+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98f8f151d0b5'
down_revision: Union[str, Sequence[str], None] = 'ad166fc97277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_packets',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('org_id', sa.String(length=128), nullable=False),
    sa.Column('object_id', sa.String(length=128), nullable=False),
    sa.Column('seq', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'seq', name='uq_telemetry_packets_device_seq')
    )
    op.create_index('ix_telemetry_packets_device_id', 'telemetry_packets', ['device_id'], unique=False)
    op.create_index('ix_telemetry_packets_object_id', 'telemetry_packets', ['object_id'], unique=False)
    op.create_index('ix_telemetry_packets_org_id', 'telemetry_packets', ['org_id'], unique=False)
    op.create_index('ix_telemetry_packets_received_at', 'telemetry_packets', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_packets_received_at', table_name='telemetry_packets')
    op.drop_index('ix_telemetry_packets_org_id', table_name='telemetry_packets')
    op.drop_index('ix_telemetry_packets_object_id', table_name='telemetry_packets')
    op.drop_index('ix_telemetry_packets_device_id', table_name='telemetry_packets')
    op.drop_table('telemetry_packets')
    # ### end Alembic commands ###
