"""cascade device deletion fks

Revision ID: 1edec7254909
Revises: 5ef5bd9329a0
Create Date: 2026-08-23 21:07:15.568301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edec7254909'
down_revision: Union[str, Sequence[str], None] = '5ef5bd9329a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_activation_codes_redeemed_by_credential_id_fkey'), 'device_activation_codes', type_='foreignkey')
    op.create_foreign_key(None, 'device_activation_codes', 'device_credentials', ['redeemed_by_credential_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('measurement_points_device_id_fkey'), 'measurement_points', type_='foreignkey')
    op.create_foreign_key(None, 'measurement_points', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurement_points', type_='foreignkey')
    op.create_foreign_key(op.f('measurement_points_device_id_fkey'), 'measurement_points', 'devices', ['device_id'], ['id'])
    op.drop_constraint(None, 'device_activation_codes', type_='foreignkey')
    op.create_foreign_key(op.f('device_activation_codes_redeemed_by_credential_id_fkey'), 'device_activation_codes', 'device_credentials', ['redeemed_by_credential_id'], ['id'])
    # ### end Alembic commands ###
