"""device state reports channel

Revision ID: ff92f8b2a23d
Revises: 1edec7254909
Create Date: 2026-09-03 19:29:18.545120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff92f8b2a23d'
down_revision: Union[str, Sequence[str], None] = '1edec7254909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_state_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('packet_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['telemetry_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('packet_id', 'section', name='uq_device_state_reports_packet_section')
    )
    op.create_index('ix_device_state_reports_device_section_captured', 'device_state_reports', ['device_id', 'section', 'captured_at'], unique=False)
    op.create_index(op.f('ix_device_state_reports_packet_id'), 'device_state_reports', ['packet_id'], unique=False)
    op.create_table('telemetry_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('packet_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('point_id', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['telemetry_packets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_errors_code'), 'telemetry_errors', ['code'], unique=False)
    op.create_index('ix_telemetry_errors_device_code_occurred', 'telemetry_errors', ['device_id', 'code', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_telemetry_errors_device_id'), 'telemetry_errors', ['device_id'], unique=False)
    op.create_index(op.f('ix_telemetry_errors_packet_id'), 'telemetry_errors', ['packet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_errors_packet_id'), table_name='telemetry_errors')
    op.drop_index(op.f('ix_telemetry_errors_device_id'), table_name='telemetry_errors')
    op.drop_index('ix_telemetry_errors_device_code_occurred', table_name='telemetry_errors')
    op.drop_index(op.f('ix_telemetry_errors_code'), table_name='telemetry_errors')
    op.drop_table('telemetry_errors')
    op.drop_index(op.f('ix_device_state_reports_packet_id'), table_name='device_state_reports')
    op.drop_index('ix_device_state_reports_device_section_captured', table_name='device_state_reports')
    op.drop_table('device_state_reports')
    # ### end Alembic commands ###
