"""update user-org relationship and security groups schema

Revision ID: 4a2eebcdc30a
Revises: remove_org_object
Create Date: 2026-08-18 18:55:03.230160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2eebcdc30a'
down_revision: Union[str, Sequence[str], None] = 'remove_org_object'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_organizations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.add_column('security_groups', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_security_groups_name'), table_name='security_groups')
    op.create_index(op.f('ix_security_groups_name'), 'security_groups', ['name'], unique=False)
    op.drop_index(op.f('ix_security_groups_system_key'), table_name='security_groups')
    op.create_index(op.f('ix_security_groups_system_key'), 'security_groups', ['system_key'], unique=False)
    op.create_index(op.f('ix_security_groups_organization_id'), 'security_groups', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_security_groups_org_name', 'security_groups', ['organization_id', 'name'])
    op.create_unique_constraint('uq_security_groups_org_system_key', 'security_groups', ['organization_id', 'system_key'])
    op.create_foreign_key(None, 'security_groups', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.drop_constraint(None, 'security_groups', type_='foreignkey')
    op.drop_constraint('uq_security_groups_org_system_key', 'security_groups', type_='unique')
    op.drop_constraint('uq_security_groups_org_name', 'security_groups', type_='unique')
    op.drop_index(op.f('ix_security_groups_organization_id'), table_name='security_groups')
    op.drop_index(op.f('ix_security_groups_system_key'), table_name='security_groups')
    op.create_index(op.f('ix_security_groups_system_key'), 'security_groups', ['system_key'], unique=True)
    op.drop_index(op.f('ix_security_groups_name'), table_name='security_groups')
    op.create_index(op.f('ix_security_groups_name'), 'security_groups', ['name'], unique=True)
    op.drop_column('security_groups', 'organization_id')
    op.drop_table('users_organizations')
    # ### end Alembic commands ###
