"""replace device shared-secret with asymmetric device_credentials

Revision ID: e4bbf30c8cc5
Revises: 4a2eebcdc30a
Create Date: 2026-08-22 09:26:33.685758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = 'e4bbf30c8cc5'
down_revision: Union[str, Sequence[str], None] = '4a2eebcdc30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_credentials',
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pending_water_object_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('pending_challenge', sa.String(length=64), nullable=True),
    sa.Column('challenge_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_device_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claimed_device_id')
    )
    op.create_index(op.f('ix_device_credentials_serial_number'), 'device_credentials', ['serial_number'], unique=True)
    op.add_column('devices', sa.Column('device_credential_id', PG_UUID(as_uuid=True), nullable=False))
    op.create_index(op.f('ix_devices_device_credential_id'), 'devices', ['device_credential_id'], unique=True)
    op.create_foreign_key(None, 'devices', 'device_credentials', ['device_credential_id'], ['id'])
    op.drop_column('devices', 'hashed_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('hashed_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('fk_devices_device_credential_id', 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_device_credential_id'), table_name='devices')
    op.drop_column('devices', 'device_credential_id')
    op.drop_index(op.f('ix_device_credentials_serial_number'), table_name='device_credentials')
    op.drop_table('device_credentials')
    # ### end Alembic commands ###
