"""init migration

Revision ID: ad166fc97277
Revises: 
Create Date: 2026-08-05 09:34:51.437275+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad166fc97277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_display_name', sa.String(length=255), nullable=True),
    sa.Column('context_type', sa.String(length=100), nullable=True),
    sa.Column('context_id', sa.String(length=255), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.execute("ALTER TABLE audit_events ADD PARTITION audit_events_default DEFAULT")
    op.create_index('idx_audit_actor', 'audit_events', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_changes_gin', 'audit_events', ['changes'], unique=False, postgresql_using='gin')
    op.create_index('idx_audit_context', 'audit_events', ['context_type', 'context_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_entity', 'audit_events', ['entity_type', 'entity_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('security_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('system_key', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_groups_name'), 'security_groups', ['name'], unique=True)
    op.create_index(op.f('ix_security_groups_system_key'), 'security_groups', ['system_key'], unique=True)
    op.create_table('security_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_permissions_category'), 'security_permissions', ['category'], unique=False)
    op.create_index(op.f('ix_security_permissions_code'), 'security_permissions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('security_group_permissions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['security_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['security_permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('security_user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['security_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_user_groups')
    op.drop_table('security_group_permissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_permissions_code'), table_name='security_permissions')
    op.drop_index(op.f('ix_security_permissions_category'), table_name='security_permissions')
    op.drop_table('security_permissions')
    op.drop_index(op.f('ix_security_groups_system_key'), table_name='security_groups')
    op.drop_index(op.f('ix_security_groups_name'), table_name='security_groups')
    op.drop_table('security_groups')
    op.drop_index('idx_audit_entity', table_name='audit_events')
    op.drop_index('idx_audit_context', table_name='audit_events')
    op.drop_index('idx_audit_changes_gin', table_name='audit_events', postgresql_using='gin')
    op.drop_index('idx_audit_actor', table_name='audit_events')
    op.execute("ALTER TABLE audit_events DROP PARTITION audit_events_default")
    op.drop_table('audit_events')
    # ### end Alembic commands ###
