[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/lewisxhe/TinyGSM-fork.git
    arduino-libraries/ArduinoHttpClient @ ^0.6.1
    bblanchon/ArduinoJson @ ^7.0.4
    adafruit/Adafruit NeoPixel @ ^1.12.0
build_flags =
    -D TINY_GSM_MODEM_A76XXSSL
    -D TINY_GSM_RX_BUFFER=1024
    -D CONFIG_ESP_TASK_WDT_TIMEOUT_S=15
    -D CONFIG_BOOTLOADER_WDT_DISABLE=1
    -Iinclude
lib_extra_dirs = ${PROJECT_DIR}/lib
